version: '3.3'
services:
  db:
    image: mysql:5.7
#    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - ./dump/:/var/lib/mysql
#    networks:
#      red_interna:
#        ipv4_address: 192.168.91.2
    container_name: mysql
  php-apache:
    build: Dockerfiles/php-apache/
    env_file:
      - .env
    links:
      - db:${MYSQL_SERVER}
    volumes: 
      - ./www/:/var/www/html
    ports:
      - ${PHP_PORT}:80
#   networks:
#      red_interna:
#        ipv4_address: 192.168.91.3
    container_name: App
#  networks:
#    red_interna:
#        ipam:
#            config:
#              - subnet: 192.168.91.1/29